module.exports.NEW_MEMBER = 'NEW_MEMBER';
module.exports.MEMBER_JOINED_ROOM = 'MEMBER_JOINED_ROOM';
module.exports.NEW_ROOM_CREATED = 'NEW_ROOM_CREATED';
module.exports.NEW_RTC_ROOM_CREATED = 'NEW_RTC_ROOM_CREATED';
module.exports.JOIN_TO_RTC_CHANNEL_SUCCESS = 'JOIN_TO_RTC_CHANNEL_SUCCESS';
module.exports.JOIN_TO_RTC_CHANNEL_FAILURE = 'JOIN_TO_RTC_CHANNEL_FAILURE';

module.exports.SERVER_MESSAGE_RECEIVED = 'SERVER_MESSAGE_RECEIVED';
module.exports.SEND_MESSAGE = 'SEND_MESSAGE';
module.exports.JOIN_TO_RTC_CHANNEL = 'JOIN_TO_RTC_CHANNEL';
