module.exports.NEW_MEMBER = 'NEW_MEMBER';
module.exports.MEMBER_JOINED_ROOM = 'MEMBER_JOINED_ROOM';
module.exports.NEW_ROOM_CREATED = 'NEW_ROOM_CREATED';

module.exports.SERVER_MESSAGE_RECEIVED = 'SERVER_MESSAGE_RECEIVED';
module.exports.SEND_MESSAGE = 'SEND_MESSAGE';
