export const NEW_MEMBER = 'NEW_MEMBER';
export const MEMBER_JOINED_ROOM = 'MEMBER_JOINED_ROOM';
export const NEW_ROOM_CREATED = 'NEW_ROOM_CREATED';
export const NEW_RTC_ROOM_CREATED = 'NEW_RTC_ROOM_CREATED';
export const JOIN_TO_RTC_CHANNEL_SUCCESS = 'JOIN_TO_RTC_CHANNEL_SUCCESS';
export const JOIN_TO_RTC_CHANNEL_FAILURE = 'JOIN_TO_RTC_CHANNEL_FAILURE';

export const SERVER_MESSAGE_RECEIVED = 'SERVER_MESSAGE_RECEIVED';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const JOIN_TO_RTC_CHANNEL = 'JOIN_TO_RTC_CHANNEL';

export const ACTION_TYPES = {
    NEW_MEMBER,
    MEMBER_JOINED_ROOM,
    NEW_ROOM_CREATED,
    NEW_RTC_ROOM_CREATED,
    JOIN_TO_RTC_CHANNEL_SUCCESS,
    JOIN_TO_RTC_CHANNEL_FAILURE,
    SERVER_MESSAGE_RECEIVED,
    SEND_MESSAGE,
    JOIN_TO_RTC_CHANNEL,
} as const;

export const ACTION_TYPES_VALUES = Object.keys(ACTION_TYPES).map((key) => ACTION_TYPES[key]);
